---
- name: tomcat installation
  hosts: webservers
  tasks:
  - name: copy and untar tomcat
    unarchive:
      src: /home/ansible/apache-tomcat-10.0.7.tar.gz
      dest: /opt/
      copy: no
  - name: copy users
    template:
      src: tomcat-users.xml
      dest: /opt/apache-tomcat-10.0.7/conf/tomcat-user.xml
  - name: copy content.xml
    template:
      src: content.xml
      dest: /opt/apache-tomcat-10.0.7/webapps/manager/META-INF/content.xml
  - name: shutdown tomcat
    command: nohup sh /opt/apache-tomcat-10.0.7/bin/shutdown.sh &
    become: true
    become_user: root
  - name: start tomcat
    command: nohup sh /opt/apache-tomcat-10.0.7/bin/startup.sh &
    become: true
    become_user: root
